In [1]:
import os
from PIL import Image
import numpy as np

# Define the folder and image names
folder = 'imgs'
imgNames = ['dog-puppy.jpeg', 'IMG_2465.jpeg', 'IMG_4365.jpeg']

# Initialize an empty list to store images
images = []

# Load each image and convert it to a NumPy array
for imgName in imgNames:
    img_path = os.path.join(folder, imgName)  # Full path to the image
    img = Image.open(img_path)  # Open the image using PIL
    img_array = np.array(img)   # Convert the image to a NumPy array
    images.append(img_array)    # Add the array to the images list

# Print the shape of the loaded images
for i, img_array in enumerate(images):
    print(f"Image {imgNames[i]} shape: {img_array.shape}")


Image dog-puppy.jpeg shape: (1197, 1200, 3)
Image IMG_2465.jpeg shape: (3024, 4032, 3)
Image IMG_4365.jpeg shape: (4032, 2268, 3)


In [6]:
import numpy as np

# Input image array (5x5)
img_array = np.array( [ [ 60, 113,  56, 139,  85],
                        [ 73, 121,  54,  84, 128],
                        [131,  99,  70, 129, 127],
                        [ 80,  57, 115,  69, 134],
                        [104, 126, 123,  95, 130]])

# Filter array (3x3)
filter_array = np.array([   [ 0, -1,  0],
                            [-1,  5, -1],
                            [ 0, -1,  0]])

# Get dimensions of image and filter
img_height, img_width = img_array.shape
filter_height, filter_width = filter_array.shape

# Output dimensions for convolution without padding
output_height = img_height - filter_height + 1
output_width = img_width - filter_width + 1

# Initialize the output array
output_array = np.zeros((output_height, output_width))

# Perform convolution operation without padding
for i in range(output_height):
    for j in range(output_width):
        # Extract the current region of the image
        region = img_array[i:i+filter_height, j:j+filter_width]
        
        # Perform element-wise multiplication and sum the result
        output_array[i, j] = np.sum(region * filter_array)

# Print the output array
print("Output after convolution without padding:")
print(output_array)

Output after convolution without padding:
[[ 266.  -61.  -30.]
 [ 116.  -47.  295.]
 [-135.  256. -128.]]


In [7]:
-129-115-95-134+(69*5)

-128

In [5]:
import numpy as np

# Input image array (5x5)
img_array = np.array( [ [ 60, 113,  56, 139,  85],
                        [ 73, 121,  54,  84, 128],
                        [131,  99,  70, 129, 127],
                        [ 80,  57, 115,  69, 134],
                        [104, 126, 123,  95, 130]])

# Filter array (3x3)
filter_array = np.array([   [ 0, -1,  0],
                            [-1,  5, -1],
                            [ 0, -1,  0]])

# Get dimensions of image and filter
img_height, img_width = img_array.shape
filter_height, filter_width = filter_array.shape

# Set padding size (p = 1 for 3x3 filter to retain the same dimensions as input)
pad = 1

# Add zero padding to the input image
padded_img = np.pad(img_array, pad_width=pad, mode='constant', constant_values=0)

# New padded image dimensions
padded_img_height, padded_img_width = padded_img.shape

# Output dimensions with padding
output_height = padded_img_height - filter_height + 1
output_width = padded_img_width - filter_width + 1

# Initialize the output array
output_array = np.zeros((output_height, output_width))

# Perform convolution operation with padding
for i in range(output_height):
    for j in range(output_width):
        # Extract the current region of the padded image
        region = padded_img[i:i+filter_height, j:j+filter_width]
        
        # Perform element-wise multiplication and sum the result
        output_array[i, j] = np.sum(region * filter_array)

# Print the padded image and output array
print("Padded image:")
print(padded_img)

print("\nOutput after convolution with zero padding:")
print(output_array)


Padded image:
[[  0   0   0   0   0   0   0]
 [  0  60 113  56 139  85   0]
 [  0  73 121  54  84 128   0]
 [  0 131  99  70 129 127   0]
 [  0  80  57 115  69 134   0]
 [  0 104 126 123  95 130   0]
 [  0   0   0   0   0   0   0]]

Output after convolution with zero padding:
[[ 114.  328.  -26.  470.  158.]
 [  53.  266.  -61.  -30.  344.]
 [ 403.  116.  -47.  295.  244.]
 [ 108. -135.  256. -128.  344.]
 [ 314.  346.  279.  153.  421.]]
